### ISSUE TITLE
Determinar UX y Paleta de colores

### ISSUE THREAD

**Issue by aldogayala14** [aldogayala14/proyectoISPC#7]
Determinar los colores que se van a visualizar en las distintas vistas. Realizar las vistas responsivas.

**Comment by matiicardozo** [comment]
Paleta de colores:
![Paleta de Colores ](https://user-images.githubusercontent.com/106358177/196993868-b118fad4-d0da-4f8a-b68e-47fb5709c09a.jpeg)

**Comment by eleonit** [comment]
UX:

![image](https://user-images.githubusercontent.com/81837768/197101030-255cfb3f-dce1-4caa-b599-eecf2d43bc66.png)
